bile_mo_app:
    resource: "@BileMoAppBundle/Resources/config/routing.yml"
    prefix:   /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }