services:
#    bile_mo_app.example:
#        class: BileMo\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
   BileMo\AppBundle\DataFixtures\MobilePhoneFixtures:
       tags: [doctrine.fixture.orm]

   BileMo\AppBundle\DataFixtures\DemoUserFixture:
       tags: [doctrine.fixture.orm]

   BileMo\AppBundle\Event\Doctrine\User\HashPasswordListener:
       autowire: true
       tags: [doctrine.event_subscriber]
