<?php

namespace BileMo\AppBundle\Repository;

/**
 * MobilePhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobilePhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
